version: '3'
services:
  toposoid-common:
    image: toposoid-common:0.6
    environment:
      - TOPOSOID_AWS_CREDENTIAL_ACCESSKEY=__##YOUR_AWS_ACCESS_KEY##__
      - TOPOSOID_AWS_CREDINTIAL_SECRETKEY=__##YOUR_AWS_SECRET_KEY##__
      - TOPOSOID_GRAPHDB_WEB_HOST=scala-data-accessor-neo4j-web
      - TOPOSOID_GRAPHDB_WEB_PORT=9005
    tty: true

  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.6
    environment:
      - PRIVATE_IP_ADDRESS=scala-data-accessor-neo4j-web
      - TOPOSOID_GRAPHDB_HOST=neo4j
      - PLAY_HTTP_PORT=9005
    ports:
      - 9005:9005

  neo4j:
    image: neo4j:4.4.23
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_transaction_timeout=10s
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/p@ssw0rd